FROM clojure:latest
MAINTAINER Timothy Washington


RUN wget https://www.yourkit.com/download/docker/YourKit-JavaProfiler-2019.1-docker.zip -P /tmp/ && \
  unzip /tmp/YourKit-JavaProfiler-2019.1-docker.zip -d /usr/local && \
  rm /tmp/YourKit-JavaProfiler-2019.1-docker.zip
EXPOSE 10001


RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY project.clj /usr/src/app


# RUN lein deps
# COPY m2 /root/.m2
# COPY !(m2) /app

ENTRYPOINT ["/bin/bash"]
