FROM clojure:latest
MAINTAINER Timothy Washington


RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean -y && \
    apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y \
    netcat \
    lsof \
    net-tools

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY project.clj /usr/src/app

# RUN lein deps
# COPY m2 /root/.m2
# COPY !(m2) /app

ENTRYPOINT ["/bin/bash"]
