FROM clojure:latest
MAINTAINER Timothy Washington


RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY project.clj /usr/src/app

# RUN lein deps
# COPY m2 /root/.m2
# COPY !(m2) /app

ENTRYPOINT ["/bin/bash"]
