version: '3.3'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:3.3.1
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - 2181:2181
  
  kafka:
    image: confluentinc/cp-kafka:3.3.1
    ports:
      - 9092:9092
      - 8082:8082
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper

  tws-paper:
    environment:
      TWSUSERID: fdemo
      TWSPASSWORD: demouser
      VNC_PASSWORD: some_pass123
    image: edgarly/ibgateway-tws-paper:latest
    ports:
      - 4002:4002  # API
      - 7497:7497
      - 5900:5900  # VNC
    tty: true
    restart: always
    entrypoint: /usr/local/bin/install-base.sh
    # entrypoint: /bin/bash

  tws-live:
    environment:
      TWSUSERID: fdemo
      TWSPASSWORD: demouser
      VNC_PASSWORD: some_pass123
    image: edgarly/ibgateway-tws-live:latest
    ports:
      - 4001:4001  # API
      - 4002:4002
      - 7496:7496
      - 7497:7497
      - 5900:5900  # VNC
    tty: true
    restart: always
    entrypoint: /usr/local/bin/install-base.sh

  app-paper:
    image: edgarly/ibgateway-app:latest
    depends_on:
      - tws-paper
    working_dir: /usr/src/app
    shm_size: 1G
    environment:
      - DISPLAY=:0.0
      - TWS_HOST=tws-paper
      - TWS_PORT=4002
      - ACCOUNT_NAME=DU542121
      - LIVE_RUN=false
      - MARKET_TREND_BY_TICKS=1
      - BUY_ON_MARGIN=0.28  # 0.25 (4x more buying power than the net liquidation value)
      - BALANCING_SELL_TYPE=TRAIL  # TRAIL | LIMIT
      - BALANCING_SELL_STANDARD_DEVIATION_MULTIPLE=0.15
      # https://blog.codecentric.de/en/2013/01/useful-jvm-flags-part-6-throughput-collector/
      # - JVM_OPTS=-server -Xms2G -Xmx4G -XX:PermSize=512m -XX:+UseParallelOldGC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=4
      # - JVM_OPTS=-server -Xms8G -Xmx8 -XX:PermSize=512m -XX:+UseG1GC -XX:MaxGCPauseMillis=200
      #   -XX:ParallelGCThreads=20 -XX:ConcGCThreads=5 -XX:InitiatingHeapOccupancyPercent=70
    ports:
      - 5554:5554
      - 8080:8080
      - 3449:3449
    volumes:
      - /Users/timothyw/Projects/edgarly/ibgateway:/usr/src/app
    entrypoint: lein trampoline run --record false

  app-live:
    image: edgarly/ibgateway-app:latest
    depends_on:
      - tws-live
    working_dir: /usr/src/app
    shm_size: 1G
    environment:
      - DISPLAY=:0.0
      - TWS_HOST=tws-live
      - TWS_PORT=7496
      - ACCOUNT_NAME=U1932856
      - LIVE_RUN=true
      - MARKET_TREND_BY_TICKS=1
      - BUY_ON_MARGIN=0.28  # 0.25 (4x more buying power than the net liquidation value)
      - BALANCING_SELL_TYPE=TRAIL  # TRAIL | LIMIT
      - BALANCING_SELL_STANDARD_DEVIATION_MULTIPLE=0.15
      # https://blog.codecentric.de/en/2013/01/useful-jvm-flags-part-6-throughput-collector/
      # - JVM_OPTS=-server -Xms4G -Xmx6G -XX:PermSize=512m -XX:+UseParallelOldGC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=4
      # - JVM_OPTS=-server -Xms8G -Xmx8 -XX:PermSize=512m -XX:+UseG1GC -XX:MaxGCPauseMillis=200
      #   -XX:ParallelGCThreads=20 -XX:ConcGCThreads=5 -XX:InitiatingHeapOccupancyPercent=70
    ports:
      - 5554:5554
      - 8080:8080
      - 3449:3449
    volumes:
      - /Users/timothyw/Projects/edgarly/ibgateway:/usr/src/app
    entrypoint: lein trampoline run --record false

  record-live-data:
    image: edgarly/ibgateway-app-paper:latest
    depends_on:
      - tws-paper
    working_dir: /usr/app
    shm_size: 1G
    ports:
      - 5554:5554
      - 8080:8080
      - 3449:3449
    volumes:
      - /Users/timothyw/Projects/edgarly/ibgateway:/usr/app
    entrypoint: lein run com.interrupt.ibgateway.record-live-data --record

  kafka-tools:
    image: confluentinc/cp-kafka:3.3.1
    depends_on:
      - zookeeper
      - kafka
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"      
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_PROTOCOL_NAME: OUTSIDE
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_PROTOCOL_NAME: INSIDE
      KAFKA_PORT: 9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
   
    tty: true
    working_dir: /usr/src/app
    entrypoint: /bin/bash
